name: build-main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: build
    timeout-minutes: 30
    env:
      JAVA_OPTS: -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libidn2-0-dev
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@21.0.2=tgz+https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz

    - name: Build JVM
      run: sbt '+kyoJVM/test'

    - name: Build JS
      run: sbt '+kyoJS/test'

    - name: Build Native
      run: sbt '+kyoNative/test'
