# name: readme
# on: [push, pull_request]
# jobs:
#   readme:
#     runs-on: ubuntu-20.04
#     timeout-minutes: 5
#     steps:
#     - uses: actions/checkout@v3.0.2
#       with:
#         fetch-depth: 0
#     - uses: olafurpg/setup-scala@v13
#       with:
#           java-version: openjdk@1.17.0
#     - name: build
#       run: sbt "checkReadme"
